version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: idc-pefindo-postgres-dev
    environment:
      POSTGRES_DB: idc_pefindo_pbk_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d idc_pefindo_pbk_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: idc-pefindo-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - dev-network

volumes:
  postgres_dev_data:
  pgadmin_dev_data:

networks:
  dev-network:
    driver: bridge
